import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to the contact page
        </h1>

        <p className={styles.description}>
          Instagram : @theworldviewbymav
          <br />
          Email : maxime.ducoin@edu.ece.fr
          <br />
          Paypal : @pleasethx2
        </p>
      </main>

      <footer className={styles.footer}>
        Powered by Mav your favorite photographer
      </footer>
    </div>
  )
}
